#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <lighthouse_manager_icons.h>

int32_t lighthouse_manager_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm lighthouse_manager!");

    return 0;
}
